// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package sqlc

import (
	"time"
)

type Bulk struct {
	ID          int32     `json:"id"`
	UpdatedAt   string    `json:"updatedAt"`
	DownloadUri string    `json:"downloadUri"`
	CreatedAt   time.Time `json:"createdAt"`
	Status      string    `json:"status"`
}
